# Travis configuration file.

language: r
cache: packages
sudo: false
warnings_are_errors: false

r_github_packages:
  - jimhester/covr
  
r_packages:
  - testthat
  
after_success:
  - Rscript -e 'covr::codecov()'
